---
- name: add ssh key for simone
  tags: always
  authorized_key:
    user: simone
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKaIrXqwWXIE1dDRnufepa0l4tOH+/w9YXiXCtYRmyhq ansible" #copied from the .ssh/